### ISSUE TITLE
Migration to MV3

### ISSUE THREAD

**Issue by chunyuema** [privacy-tech-lab/gpc-privacy-choice#168]
Due to Chrome's restriction on MV3, we are now migrating the extension to use Manifest Version 3. All functionalities will be preserved.

**Comment by SebastianZimmeck** [comment]
As we discussed, @chunyuema will focus on the database, @ekuller on the `webRequest` API, and @bella-tassone will take a look at what breaks when running. This is just an initial work distribution. Let's work together, communicate, and identify the fine-grained issues that we need to tackle.

I created a milestone as a guideline to finish the switch from v2 to v3 in four weeks.

@chunyuema will take the lead on distributing work and identifying concrete issues to work on.

**Comment by chunyuema** [comment]
A quick checkpoint for MV3 migration: the new extension is semi-working under MV3, we are reconnected with DB and writing data successfully. Thank you @ekuller for updating the firestore functions. The front end is also working fine. It seems that from a user's perspective, we have nothing major breaking at this moment.

However, we still have global variables used as cache in the firebase.js script for updating the GPC signals. Due to the [restrictions of service workers on global variable](https://blog.shahednasser.com/chrome-extension-tutorial-migrating-to-manifest-v3-from-v2/), it is not recommended to use global variables as they are cleared when service worker is not running. I am looking into this.

I am also refactoring the code along the way to make sure that the code base has a better and cleaner organization of code.

**Comment by SebastianZimmeck** [comment]
Very nice progress!

**Comment by bella-tassone** [comment]
While testing the new codebase, I've found that the "Review or modify settings" button no longer works correctly. It seems instead to refresh the page. This occurred on scheme 0, but I am not sure if it applies to the other scheme as of yet. I will look further into this.

**Comment by chunyuema** [comment]
Thank you for pointing this out, @bella-tassone. It is also happening to scheme 1, which is expected to work the same. Let's create a separate issue to address any UI bugs we can identify and fix them there.

**Comment by chunyuema** [comment]
I am closing this issue. The tasks we are working on now will be #170 #171 and #172
