### ISSUE TITLE
Refactor Options page

### ISSUE THREAD

**Issue by chunyuema** [privacy-tech-lab/gpc-privacy-choice#175]
The options page is unnecessary complicated and often results in confusion while developing. This is a legacy issue from Optmeowt, which has more complicated logic for the options page. We should refactor this once we are done with what we have at the moment. I think it should just be something like a html page + a js page. Let's simplify this structure. 
![image](https://user-images.githubusercontent.com/57780561/153765901-c33fb6af-4533-4b37-8f37-4c1c308a2d2e.png)

**Comment by SebastianZimmeck** [comment]
Cc'ing @kalicki1 and @OliverWang13.

**Comment by chunyuema** [comment]
While working on #176 , I have noticed that the refactoring should be done in parallel. I spend quite a lot of time going back and forth because of the unclear code base structure on the domain list section (mostly unclear functions of each file). Closing this issue and addressing this in 176.
