### ISSUE TITLE
Test and Fix Issues

### ISSUE THREAD

**Issue by chunyuema** [privacy-tech-lab/gpc-privacy-choice#183]
We will run the same kind of test as last time with the following scheme assignments:

- [x] Scheme 1 @SebastianZimmeck 
- [x] Scheme 2 @bella-tassone 
- [x] Scheme 3 @chunyuema 
- [x] Scheme 4 @ekuller 
- [x] Scheme 5 @chunyuema 
- [x] Scheme 6 @ekuller 
- [x] Scheme 0 @bella-tassone 

Please monitor both the **UI behavior** and **database entries**. Report any issues here and we will fix them in the next two weeks

**Comment by chunyuema** [comment]
Existing issues:

- [ ] local storage for domains need to be fixed @ekuller 
- [ ] service worker sleeping issue @chunyuema

**Comment by SebastianZimmeck** [comment]
@chunyuema, could you remind me, can I change in the background.js

```
let userScheme = Math.floor(Math.random() * 7); 
```
to 

```
let userScheme = 1;
```

if I want to test Scheme 1? Or how would I do it?

**Comment by SebastianZimmeck** [comment]
Also, don't we need to test Scheme 0, too?

**Comment by chunyuema** [comment]
@SebastianZimmeck Sorry for the late reply. Yes, we need to manually set the scheme number (e.g. 1) for testing. My apologies for missing out scheme 0. I will add it in rn.

**Comment by chunyuema** [comment]
> Existing issues:
> 
> * [ ]  local storage for domains need to be fixed @ekuller
> * [x]  service worker sleeping issue @chunyuema

This is the reason for the existing issues at this moment: 

In scheme 3 & 4, when toggling the individual domains, errors occur at `cannot create property for bool`
![image](https://user-images.githubusercontent.com/57780561/159168469-b79670d2-1df1-4944-b43c-88fb1f8f776d.png)

In scheme 3 & 4, when toggling the profiles choices, errors occur at `updatePrefScheme3` or `updatePrefScheme4` undefined. Did anyone delete these functions? @SebastianZimmeck @bella-tassone @ekuller. I will and check if I deleted them by accident too.
![image](https://user-images.githubusercontent.com/57780561/159168655-da5fca40-2e2e-4b5c-b766-e6f0c87295bf.png)

In general, the local storage for domains is not updated properly. We need to work on this as the UI is built from it.

**Comment by SebastianZimmeck** [comment]
> Did anyone delete these functions?

No, I did not delete those.

**Comment by chunyuema** [comment]
More Issues: 

- [ ] The toggle of particular domains in scheme 3 is not working. It does not respond to the user's toggle. However, the domain toggle for scheme 4 is working even though they rely on the same code to work. I attempted to solve this today but did not succeed. I think I might be missing something that is rather obvious, but documenting it here...

- [ ] All Sites or All Other Sites?: we updated scheme 4 to be All Sites. At least for now, this following situation can happen, which I found to be a bit counterintuitive. Should not All Sites turn GPC on for everything?
![image](https://user-images.githubusercontent.com/57780561/161411736-57b5d7ee-44db-4bf9-b543-f98ac698c68c.png)

**Comment by SebastianZimmeck** [comment]
Good that you discovered those, @chunyuema. 

> I think I might be missing something that is rather obvious, but documenting it here...

@ekuller or @bella-tassone, could one of you also take a look at that?  

> Should not All Sites turn GPC on for everything?

Yes, if All Sites is selected --- independently of whether or not other categories are selected as well --- GPC should be turned on for every domain and GPC signals should be sent to every domain.

As an aside, I guess there could be an issue if a user unselects All Sites and now there is just, say, Analytics, selected. Would now only Analytics domains selected and GPC signals sent to those? Probably, not right? That would require to keep track of which domains are Analytics domains and upon unselecting All Sites doing a pass of re-toggling the domains in the domain list. That would seem too complicated to me. An easier approach might be to just apply the user selection going forward, i.e., leave all domains selected that were selected when All Sites was on. And once it is off, only select Analytics domains. This relates to the general question of how we deal with past/future selections in other schemes, which I am not totally aware of at the moment.

Not sure if it helps in any way, but disallowing to select any other categories as long as All Sites is selected may also be an option.

**Comment by bella-tassone** [comment]
@SebastianZimmeck, @chunyuema I can definitely take a second look at that! As for the inconsistency with the "All Sites" label, @ekuller and I noticed this, and rather than mess around with the UI any more than we already have, decided to solve the issue using the pop-up that you get when you hover on the card. As you can see below,
<img width="1404" alt="Screen Shot 2022-04-03 at 12 33 20 PM" src="https://user-images.githubusercontent.com/54873610/161438168-5551103e-09e5-4d44-a563-fa334b065e98.png">
when you select the "All Sites" card, it tells you that by selecting it, the algorithm will disregard any other cards that you may have/have not selected. If you feel that this isn't rigorous enough of a solution, we could perhaps add another pop-up that'll occur when the user hits submit, in order to confirm that the user understands what they're doing when they select "All Sites." Let me know what you think!

**Comment by SebastianZimmeck** [comment]
> Let me know what you think!

Thanks, @bella-tassone! The solution your are saying works for me. Though, if I understand @chunyuema correctly, that is actually not what is happening. As @chunyuema is saying:

> Should not All Sites turn GPC on for everything?

So, @bella-tassone, can you investigate, if a user selects All Sites and some other category, are really all sites now selected to receive GPC signals in the domain list? (@chunyuema, please clarify in case I am misunderstanding your point.)

**Comment by chunyuema** [comment]
@SebastianZimmeck @bella-tassone I found the card selection okay. However, what was confusing for me was that when I selected ALL SITES option, 33 across on the list stays as turned off. If ALL SITES sends GPC to all, I feel that the 33 across UI should be updated.

**Comment by SebastianZimmeck** [comment]
OK, so if a user initially selects All Sites and then some other category, all domains are selected, right?

If they select all sites later (your situation, @chunyuema), I can live with how it currently is (kind of "all sites for the future"). But if it is easy to update, that would work even better.

Then there is the situation that a user unselects All Sites, does that mean now that again we have to update and now do the domain list according to the categories. Again, I am fine with the meaning "not all sites for the future."

So, the bottom line is, if that update functionality is straightforward to implement it would be great. But if not, I am OK with leaving it as is.

**Comment by bella-tassone** [comment]
The 'All Sites' issue has been fixed and pushed! Now, if 'All Sites' is selected, then GPC signals should be sent to all domains.

**Comment by SebastianZimmeck** [comment]
> Now, if 'All Sites' is selected, then GPC signals should be sent to all domains.

@bella-tassone, can you clarify? 

- Sites in the domain list are updated if a user at some point after initial category selection selects All Sites (i.e. domains that were previously not receiving GPC signals are receiving them now)?

- What about the reverse (i.e., a user unselects All Sites at some point after initial category selection)? If a site a user visited is now not covered anymore by a category, is it updated to not receive GPC signals?

**Comment by bella-tassone** [comment]
> * Sites in the domain list are updated if a user at some point after initial category selection selects All Sites (i.e. domains that were previously not receiving GPC signals are receiving them now)?
> * What about the reverse (i.e., a user unselects All Sites at some point after initial category selection)? If a site a user visited is now not covered anymore by a category, is it updated to not receive GPC signals?

Yes, both of these situations should be covered, and reflected by changes in the toggles.

**Comment by SebastianZimmeck** [comment]
Excellent! Then, please feel free to open a PR and close this issue when ready.
