### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-privacy-choice#187]
- New screenshots
- Change the link of the footer file as the file is in a directory in the repo
- ...

**Comment by chunyuema** [comment]
I can also help adding [the architectural overview](https://github.com/privacy-tech-lab/gpc-privacy-choice/issues/171#issuecomment-1053591081) of the extension when @bella-tassone works on the readme.

**Comment by SebastianZimmeck** [comment]
Sounds good! @bella-tassone, if you can take the lead here and let @chunyuema know.

**Comment by chunyuema** [comment]
I added the architectural overview directly to the main branch. @bella-tassone, just make sure to pull, and there should not be any conflicts we need to worry about.

**Comment by SebastianZimmeck** [comment]
Seems the readme is (still) outdated. We probably need new screenshots for some of the scheme banners and backend screenshots. Also, we need to add the alt descriptions for the images. Let's also have less whitespace in the backend pictures as that blows up the size of pictures and does not add anything.

**Comment by bella-tassone** [comment]
I believe I have taken care of all the current revisions to the readme, so I will be closing this issue
