### ISSUE TITLE
Investigate mysterious scheme switching bug

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-privacy-choice#188]
As I said on MS Teams:

> Yesterday, I installed our extension.
I was on the scheme for selecting categories, Advertising, Analytics, ..., All Sites.
And today I am suddenly on the learning scheme.
Also, all the domain I visited in the domain list are gone, and, I think, I am only seeing the domains I visited since the switch to the new scheme.
I am not sure, did I accidentally re-install the extension?
On Firestore, I am still the same user and it says Scheme 4.

On @ekuller's question:

> Did it show you the registration page again?

> I believe, I left the tab open with the signup registration yesterday night (after having registered).
And then in the morning I believe it reloaded.
And so maybe I accidentally registered again (or that happened automatically).
That is my best explanation.

@chunyuema added:

> It might happen if the browser previously tested with scheme 5
Which might set something in the local storage and then interfere with the new one that is installed

Me:

> Ah, OK, so you are saying maybe a few weeks back I was on scheme 5.

@chunyuema:

> If this is true I m decently sure that is why there is this sudden switch. It happened to me a couple of times before

Today, I am on yet another scheme, the profile scheme (high, medium, low privacy sensitivity). I am pretty sure I did not leave the settings page open when I closed the browser. Yet, it still loaded. (I am using the most recent version of Brave, for what it is worth). 

Also --- very important --- it looks like the Firestore database stopped recording data the moment I switched to the learning scheme. (I still have our extension installed and everything looks normal.) So, I re-installed our extension, a new user was created on Firestore, and I am seeing my data now being received. So, the good news is that if a mysterious scheme switching occurs, the backend seems to stop recording. So, if we keep a close eye on what is going on at the backend, we will be able to identify the problem and alert the user to re-install our extension.

I have tried to reproduce the result by restarting my computer, restarting my browser, and trying on Chrome, but it was not possible.

Let's move on Tuesday and get the study started. So, if everyone can investigate by Monday the latest.

**Comment by chunyuema** [comment]
This problem is probably very difficult to reproduce. I have encountered it maybe 3 times in total in the past few months while we worked on the developed. 

> Also --- very important --- it looks like the Firestore database stopped recording data the moment I switched to the learning scheme. (I still have our extension installed and everything looks normal.)

It is also worth checking if a user is on scheme 5, when the scheme switch happens, does the firestore also stop recording?

**Comment by SebastianZimmeck** [comment]
> It is also worth checking if a user is on scheme 5, when the scheme switch happens, does the firestore also stop recording?

For me it stopped recording. But that is with the weird behavior I encountered, i.e., switch from scheme 4 to 5. Not sure what happens if a user starts out with scheme 5 in first place. I would hope that that records.

**Comment by chunyuema** [comment]
I am very sure that this is a problem that the users will not encounter unless they were previously on our scheme 5, and later has to reinstall the extension due to some reasons. A way to replicate the same problem is as follows: set the scheme number to be 5 in the background.js, proceed with the rest of the work. Before the learning phase finish, restart the extension with another scheme, at some point using this new scheme, you will encounter the problem of scheme switching.

**Comment by SebastianZimmeck** [comment]
OK, thank you, @chunyuema! I'd say, let's leave it then. We will be alerted in the rare case where this may happen by not seeing data written to the database anymore. At that point, we can contact the participant and figure it out.
