### ISSUE TITLE
What does GPC Current Site / Global Status"unset" mean?

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-privacy-choice#189]
I have made a banner decision in scheme 0 (choice banner and mute button) to send GPC signals to ft.com. The domain interaction history correctly shows the decision:

<img width="457" alt="Screen Shot 2022-04-16 at 10 27 10 AM" src="https://user-images.githubusercontent.com/11034003/163678852-ff759f4a-05e3-4360-92e0-d30c6cef9745.png">

However, when I visit the site again, the browser history shows GPC Current Site / Global Status"unset."

<img width="409" alt="Screen Shot 2022-04-16 at 10 26 45 AM" src="https://user-images.githubusercontent.com/11034003/163678869-8a454b40-7778-4be7-84ef-45dc08287af4.png">

So, it seems that the value has no meaning. Are we just going according to the domain interaction history?

**Comment by chunyuema** [comment]
I notice this issue too. I do not think it used to be like this. There might be a bug somewhere.

**Comment by chunyuema** [comment]
I am working on this issue. Just identified the source of the problem.

**Comment by chunyuema** [comment]
GPC Current Site Status: 
- unset means the user has never explicitly made a GPC decision on the site, whether it is from the banner or from the options page

GPC Global Status:
- unset means that the user has never explicitly made a GPC decision on a global setting, whether it is from the banner or from the options page

Therefore, it is possible to see combinations such as: 
current = unset, global = true / false
current = true / false, global = unset

**Comment by SebastianZimmeck** [comment]
Nice! Thank you, @chunyuema!

**Comment by SebastianZimmeck** [comment]
One clarification question on GPC Current Site Status.

Here I am seeing `unset`.

<img width="1091" alt="Screen Shot 2022-05-19 at 4 19 30 PM" src="https://user-images.githubusercontent.com/11034003/169397542-b34988b8-2b6c-4e47-bd2b-035b562418e8.png">

And then for the same domain but a different path I see `false`.

<img width="1104" alt="Screen Shot 2022-05-19 at 4 20 14 PM" src="https://user-images.githubusercontent.com/11034003/169397675-58b81fc0-3d5e-4b3b-8011-ada8fdaf85e2.png">

This is because there were no third party requests on the page in the first case?

I did not make any changes to the configuration in between visiting these two.

<img width="1085" alt="Screen Shot 2022-05-19 at 4 22 08 PM" src="https://user-images.githubusercontent.com/11034003/169397904-e09b81fc-6285-464f-90a2-ae2f1125ad78.png">

<img width="1099" alt="Screen Shot 2022-05-19 at 4 23 20 PM" src="https://user-images.githubusercontent.com/11034003/169398100-1b874c92-c1e6-4232-b0a2-0dd428f8ed13.png">

If Advertising (or Analytics) would have been selected in the configuration, I would presumably have seen `true`?

**Comment by SebastianZimmeck** [comment]
As discussed, this actually seems to work as intended (see my readme additions). @ekuller will take a final look at this to make sure it works.

I added the following to the readme on the know issues:

> - **GPC Current Site Status**, i.e., whether GPC is enabled on a site or not does show a result on Firebase when the site is visited the first time. It shows "N/A". The reason is that at the moment the site is visited the first time, the user has not yet made a GPC choice. The GPC Current Site Status corresponds to the GPC status in the domain list.

I also added the following to the scheme section for profiles (and equivalent for the category scheme):

> Scheme 3 makes use of **Privacy Profiles**. Upon running the extension for the first time, users are prompted to choose a privacy profile. Their choice will then determine which sites will receive GPC signals. We use the [disconnect-tracking-protection list](https://github.com/disconnectme/disconnect-tracking-protection) to identify sites that should receive signals under a certain Privacy Profile. Users can select to which domains they want to send GPC signals via a domain list on the Options Page. The GPC values for domains on the domain list depend on in which category, if any, the domain is included in the disconnect-tracking-protection list as well as the choices a user makes on the domain list.

**Comment by ekuller** [comment]
> As discussed, this actually seems to work as intended (see my readme additions). @ekuller will take a final look at this to make sure it works.
> 
> I added the following to the readme on the know issues:
> 
> > * **GPC Current Site Status**, i.e., whether GPC is enabled on a site or not does show a result on Firebase when the site is visited the first time. It shows "N/A". The reason is that at the moment the site is visited the first time, the user has not yet made a GPC choice. The GPC Current Site Status corresponds to the GPC status in the domain list.
> 
> I also added the following to the scheme section for profiles (and equivalent for the category scheme):
> 
> > Scheme 3 makes use of **Privacy Profiles**. Upon running the extension for the first time, users are prompted to choose a privacy profile. Their choice will then determine which sites will receive GPC signals. We use the [disconnect-tracking-protection list](https://github.com/disconnectme/disconnect-tracking-protection) to identify sites that should receive signals under a certain Privacy Profile. Users can select to which domains they want to send GPC signals via a domain list on the Options Page. The GPC values for domains on the domain list depend on in which category, if any, the domain is included in the disconnect-tracking-protection list as well as the choices a user makes on the domain list.

Looks good to me.
