### ISSUE TITLE
Fix "Review or modify your settings" bug

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-privacy-choice#190]
When I visit the site of the [Hartford Public Library](https://hplct.ent.sirsi.net/client/en_US/default/) with scheme 0, I am shown the banner, and I click on "Review or modify your settings," I am not redirected to the settings page. Rather, the Hartford Public Library site is reloaded. The same happens on [coinbase](url). So, I am assuming this is not an isolated incident of one site breaking but a fundamental issue. 

Please also check the other schemes with links to "Review or modify your settings," in banners or wherever they are, to make sure the link is working everywhere.

**Comment by bella-tassone** [comment]
So I've been looking into this issue, and I actually think it's deeper than just the review/modify settings button. Upon clicking "Enable GPC", I seemed to trigger a sort of loop:
<img width="763" alt="Screen Shot 2022-04-17 at 8 34 27 PM" src="https://user-images.githubusercontent.com/54873610/163738204-f9bd9cf3-044e-4e72-90cd-704feb1b7e41.png">
So I think there is an issue with our listeners... I'm not sure why this is occurring though. Will continue to look into it, but if @ekuller or @chunyuema could take a quick look into this as well it might be helpful!

**Comment by chunyuema** [comment]
I will look into this issue now.

**Comment by SebastianZimmeck** [comment]
Thank you, @chunyuema!

**Comment by ekuller** [comment]
The problem is just that there is not an appropriate recipient in the service worker to receive the message that is sent when the link is pressed (could've been accidentally deleted at some point?). @chunyuema I can push the fix if you want.
