### ISSUE TITLE
Increase snooze duration for scheme 0

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-privacy-choice#191]
As I am testing scheme 0, I can imagine that the 6 hours snooze duration can still be annoying. Participants may actually quit the study. Can we increase that to 12 hours? (Or do you have other thoughts?)

**Comment by chunyuema** [comment]
I am okay with increasing the snooze duration to 12 hours.

**Comment by SebastianZimmeck** [comment]
OK, if @ekuller and @bella-tassone, have no objections either, could you go ahead, @chunyuema?

(I am assuming this is trivial and involves just changing some numbers in the code.)

**Comment by chunyuema** [comment]
@bella-tassone will work on this issue.
