### ISSUE TITLE
Scheme Interference in GPC signal recording [Scheme 6]

### ISSUE THREAD

**Issue by chunyuema** [privacy-tech-lab/gpc-privacy-choice#198]
We observed that GPC current page setting in scheme 6 is sometimes recorded as "false" but it should always be "unset". This indicates that code for other schemes are interfering with scheme 6.

**Comment by SebastianZimmeck** [comment]
If this issue is fixed, the description of this quirk in the readme under "7. Known Issues" needs to be modified or deleted.
