### ISSUE TITLE
Domain deletion [Scheme 5]

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-privacy-choice#200]
Just to clarify, if we see something like below (for scheme 5), it just means a user deleted a domain? Or what does `null` mean?

<img width="435" alt="Screen Shot 2022-05-13 at 3 03 38 PM" src="https://user-images.githubusercontent.com/11034003/168371001-87827778-49f0-48da-bb05-1591deec6660.png">

**Comment by SebastianZimmeck** [comment]
Is this related to #201? Does anyone know?

**Comment by chunyuema** [comment]
This should be normal. If the title is deleted, we just interpret this as a user deletion. The interaction field is irrelevant in this case. I believe that it is intentionally set to null.

**Comment by SebastianZimmeck** [comment]
Sounds good!
