### ISSUE TITLE
Fix terminology "Not Privacy Sensitive" vs "Low Privacy-Sensitivity" [Scheme 3]

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-privacy-choice#203]
They seem to mean the same thing. Maybe, just use "Low Privacy-Sensitivity"? Maybe, this is populated from different parts of the codebase. It's probably just relevant for scheme 3 as the other schemes do not include the profiles. But let's make sure.

**Comment by bella-tassone** [comment]
I actually already fixed this when making the other scheme 3 changes. So we're all set here!

**Comment by SebastianZimmeck** [comment]
Great! Feel free to close then if there is nothing more to do, @bella-tassone.
