### ISSUE TITLE
Address issue with extension breaking for some users

### ISSUE THREAD

**Issue by ekuller** [privacy-tech-lab/gpc-privacy-choice#205]
After some use, the extension stops working for some users:
- browser history is not recorded
- pop up stops appearing

**Comment by SebastianZimmeck** [comment]
And domain interaction history seems to stop being collected at the same time as browsing history. So, essentially, the whole backend connection seems gone at this point.

@chunyuema says:

> It is likely that the service worker goes to sleep and never wake up in the cases when all information suddenly stops. I believe that this is a known issue for the MV3. I added a piece of code to send some messages from the content script to the service worker to keep it alive but maybe that is not working completely.

**Comment by SebastianZimmeck** [comment]
It seems difficult to find out why some users report that they have installed our extension, but we do not seem to receive complete data. Closing this for now as this could also be an issue on the users' end. We have to see ...
