### ISSUE TITLE
Domain GPC signal showing up as false when unset

### ISSUE THREAD

**Issue by ekuller** [privacy-tech-lab/gpc-privacy-choice#207]
- Clarify what GPC Current Site Status Means
- make sure it is working that way

**Comment by chunyuema** [comment]
Discussion outcome: 
- GPC Current Site Status: **True/False** if and only if a user mades an explicit decision either through banner or through options page; otherwise **Unset**

**Comment by SebastianZimmeck** [comment]
Indeed. And to clarify, the selection of a profile or category does not impact the GPC Current Site Status, i.e., it remains `unset`.
