### ISSUE TITLE
Implement domain list for scheme 6

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-privacy-choice#208]
I think it would be good to implement the domain list for scheme 6. More on that later today or tomorrow. @bella-tassone, I assigned you for the time being. Maybe, @ekuller and/or @chunyuema can help out.

**Comment by SebastianZimmeck** [comment]
I realize this may be already implemented. Per the readme:

> They may change this preference on the Options Page. 

@bella-tassone, that is the case, right?

**Comment by bella-tassone** [comment]
Hi @SebastianZimmeck , I just checked, and it actually isn't the case. I believe we had decided against the domain list for scheme 6 because it's supposed to be our all-or-nothing scheme, with no personalization whatsoever.

**Comment by SebastianZimmeck** [comment]
OK, thanks, @bella-tassone. We should included it, I think.

**Comment by SebastianZimmeck** [comment]
@bella-tassone, it would also be good if you can add a sentence on the page where users make their choice that they can make modifications in the domain list. Not sure how we do this in other schemes with domain list, but this should be exactly in the same way here.

**Comment by SebastianZimmeck** [comment]
I believe this is done. Feel free to reopen @chunyuema or @bella-tassone if that is not the case.
