### ISSUE TITLE
Clarify third party library use

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-privacy-choice#209]
@ekuller, if you could take a brief look at the library list in the readme, update it as necessary, and also clean up the code (e.g., if we no longer use a particular library).

**Comment by ekuller** [comment]
I believe [FileSaver.js](https://github.com/eligrey/FileSaver.js) and [psl (Public Suffix List)](https://github.com/lupomontero/psl) are not used. Nothing obvious is wrong when I delete the libraries. @chunyuema and @bella-tassone do you think otherwise? If not, I will go ahead and get rid of them.
