### ISSUE TITLE
Address ad interactions duplicate entries

### ISSUE THREAD

**Issue by ekuller** [privacy-tech-lab/gpc-privacy-choice#215]

**Comment by SebastianZimmeck** [comment]
Here is an example:

<img width="1119" alt="Screen Shot 2022-05-26 at 9 48 53 AM" src="https://user-images.githubusercontent.com/11034003/170507202-ce3c92b4-ff3d-47b2-b6b1-7defed230e71.png">

<img width="1127" alt="Screen Shot 2022-05-26 at 9 49 02 AM" src="https://user-images.githubusercontent.com/11034003/170507241-a87fda22-8682-43f2-92ad-8344a7e76a61.png">

If these are technically just two different interactions, the setup can stay as is from my side. This is assuming that the behavior is consistent for all such instances. We can also settle on a different recording, but again, it should be consistent across all instances.

**Comment by SebastianZimmeck** [comment]
Same here, would be good to have finalized by Monday night.

**Comment by ekuller** [comment]
This no longer seems to be happening. If it happens again, we can deal with it when cleaning up data.
