### ISSUE TITLE
Attempt to create scheme-specific collections in database

### ISSUE THREAD

**Issue by bella-tassone** [privacy-tech-lab/gpc-privacy-choice#223]
I think it would be beneficial to have the data separated by scheme in firestore. This way, we wouldn't have to wipe the database every time we release a new scheme, and we could also export scheme-specific JSON files. I believe implementing this means messing with the firestore security rules, so I'm going to wait to try it until after data collection for scheme 1 is done.

**Comment by SebastianZimmeck** [comment]
OK, sounds good. As a cautionary measure, it may be good to download the data before making any changes to Firebase to avoid accidental deletions or confusions that we would need to sort out later.

> I think it would be beneficial to have the data separated by scheme in firestore. 

@chunyuema or @ekuller, if it so happens that you are aware of any considerations or Firebase workings in this regard, I would appreciate your comment (no worries if you are busy).

**Comment by bella-tassone** [comment]
I believe I've made a breakthrough here. By slightly altering the firebase security rules, I've successfully been able to create a second collection titled "users-scheme2." This is where I plan to send the user data for scheme 2. I will close this issue after a little more testing.

**Comment by SebastianZimmeck** [comment]
Excellent!
