### ISSUE TITLE
Reference Domain List in Registration for Schemes 3-6

### ISSUE THREAD

**Issue by bella-tassone** [privacy-tech-lab/gpc-privacy-choice#225]
>However, I think it would be beneficial to include maybe a **sentence** in the registration tab for schemes 3-6 that pointed out the Options page, and let users know they could make individual domain decisions there. Let me know how you feel about this compromise!

I will add a sentence or two to the registration page for schemes 3-6 that makes sure users are aware of the domain list in the Options page.

**Comment by bella-tassone** [comment]
<img width="1165" alt="Screen Shot 2022-06-15 at 10 35 04 AM" src="https://user-images.githubusercontent.com/54873610/173853950-fab74a32-6caf-4d9e-9ff9-1959d08dce26.png">

This is what I was thinking... let me know if you have any suggestions!

**Comment by SebastianZimmeck** [comment]
Yes, that is good! 

Is "Options page" a link? If not, can that be a link to chrome-extension://ambkmcacbikgdchhjohhkfngeahpolnk/options/options.html

Also make it a little more clear with "If you wish to further personalize you privacy choices, you may individually select the domains which should be permitted or prohibited from selling/sharing your data on the options page."

That should work for 3, 4, and 6. I am not sure about the learning scheme (scheme 5). Do we show users any pop-up screen or just the "learning has finished" screen?

**Comment by bella-tassone** [comment]
As I noted before, it doesn't really make sense for "Options page" to be a link because:

- We need the _first_ thing they do to be filling out the registration form. If that doesn't happen, then data does not get recorded, which is an issue.
- Since the link is on the registration page, there will not be anything to do on the Options page yet, as the user has not visited any domains. The only way there would be domains on the Options page at that point is if the user didn't submit the registration form before visiting other sites, which we **do not want** for the reason noted above.

I can make the language changes though! And I agree that the learning scheme (5) is probably alright as is because the user already gets transferred to the Options page as soon as the learning is finished.

**Comment by SebastianZimmeck** [comment]
OK, I understand your reasoning. I suggested it as I am not sure users understand where the options page is. It is true that they could not do anything. Though, I am a bit worried that they do not understand what we mean by referring to the "options page." Maybe, we say in the "extension settings" instead of "options page"? Would that be more clear? Or do you think "options page" is clear?

**Comment by bella-tassone** [comment]
<img width="553" alt="Screen Shot 2022-06-15 at 11 31 04 AM" src="https://user-images.githubusercontent.com/54873610/173866795-25b2a645-4175-4c5d-80ac-ada369375a48.png">

What if we use "settings page"? This might be beneficial because it is how we refer to the settings in the gif that shows users how to get to the settings.

**Comment by SebastianZimmeck** [comment]
OK, that is a good idea! Let's use then the following (without a link but "settings page" bold as you have for "options page"):

"If you wish to further personalize you privacy choices, you may individually select the domains which should be permitted or prohibited from selling/sharing your data on the settings page."

**Comment by bella-tassone** [comment]
Done! Creating PR now, will close this issue as it's completed.
