### ISSUE TITLE
Implement scheme for sending GPC signals depending on data categories shared (scheme 7)

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-privacy-choice#229]
As discussed today with @bella-tassone, it would be interesting to implement one more scheme, scheme 7, according to which users select sites to send GPC signals based on the type of data a site shares or sells. Here are the different data types that we could use (from one of our survey questions).

<img width="714" alt="Screen Shot 2022-06-21 at 9 42 24 AM" src="https://user-images.githubusercontent.com/11034003/174814960-8addd005-2060-4c9e-9322-2b890cece1c1.png">

For example, if a user selects Phone number, then all web requests containing the user's phone number (and possibly additional data types) would have GPC enabled. All requests that do not contain the phone number would not receive GPC signals.

As @bella-tassone pointed out, at the Firebase backend, we would need to implement something similar as the profile or recipient category scheme. We may be able to essentially just use those schemes as a blueprint.

This scheme would be a pure frontend implementation without actually sending GPC signals as we do not have functionality to filter web requests according to data categories (which we are working on in [Privacy Pioneer](https://github.com/privacy-tech-lab/privacy-pioneer)).

If we want to add this scheme, we should aim to have it finalized within the next three weeks or so (to also leave some wiggle room for testing).

As an aside, we have to be careful of testing this scheme to not mix up any test data with real data on Firebase.

I would need to submit an IRB protocol change.

**Comment by SebastianZimmeck** [comment]
> I have fully implemented scheme 7

Very nice! Thus, that include writing to the Firebase backend as well?

> I don't think it would make sense for scheme 7 to have a domain list since there isn't any backend implementation. ... so I suggest we forgo the domain list in this scheme.

Yes, I agree. One could think of a domain list that has each data type per domain, but that may be too much detail and from a practical perspective for us a lot of effort to implement. So, yes, let's remove the domain list from this scheme.

> we would need to come up with a solution that prevents users from realizing this is a dummy scheme

I will look into the IRB how to best present this to our study participants.

**Comment by bella-tassone** [comment]
Yes, the firebase backend is set up! Just need more testing.

**Comment by SebastianZimmeck** [comment]
Once it is done, we also need to add a description and screenshot of scheme 7 to the readme.
