### ISSUE TITLE
Implement note for participants that they cannot rely on scheme 7 being fully functional

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-privacy-choice#237]
It would be good to let study participants know (I am thinking on the [registration and option screens](https://github.com/privacy-tech-lab/gpc-privacy-choice/issues/229#issuecomment-1163450774)) that they should "not rely on being opted out as our extension is not a full implementation of the described functionality" or something similar. We never claim one way or the other. But for the other schemes we have a fully working (header) implementation, which is not the case for scheme 7.

**Comment by bella-tassone** [comment]
Should this only be implemented on scheme 7? Or all future schemes? @SebastianZimmeck

**Comment by SebastianZimmeck** [comment]
Scheme 7 would be sufficient in my mind because the other schemes are functional.
