### ISSUE TITLE
Add instructions to readme on how to add new schemes

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-privacy-choice#240]
It would be helpful for future researchers who want to use our extension to know how they can create their own schemes. I imagine like a list with a few bullet points fairly abstract. Just which files they would need to work on. This could be a subsection of the scheme section after scheme 7.

**Comment by bella-tassone** [comment]
I've started working on this. It's still incomplete and messy, but it's a good start. I'll continue developing it when I can, but for now it isn't a priority.

**Comment by SebastianZimmeck** [comment]
@ekuller, is it clear to you per the readme how one could add new schemes? Is there anything that would need to be added?

**Comment by SebastianZimmeck** [comment]
In general, this looks good to me. @ekuller will take a brief look and make additions or changes. Then, we can close this issue.

**Comment by SebastianZimmeck** [comment]
@ekuller, take a look, and then we can close this issue.
