### ISSUE TITLE
Develop Documentation on Running Research

### ISSUE THREAD

**Issue by bella-tassone** [privacy-tech-lab/gpc-privacy-choice#249]
More of a reminder so I don't forget before I go on vacation😁

**Comment by SebastianZimmeck** [comment]
Can you clarify, @bella-tassone, what should be documented here and where?

**Comment by bella-tassone** [comment]
Just the specifics of how I've been running the research. How I fill out the excel sheet, how to publish/close a survey, etc.

**Comment by SebastianZimmeck** [comment]
Ah, OK, sounds good!
