### ISSUE TITLE
Update readme on Privacy Configuration Interaction History

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-privacy-choice#250]
Should scheme 7 be added to the below?

> The Privacy Configuration Interaction History covers the privacy choices users make for schemes 3, 4, 5 and 6. It covers the initial choice upon registration as well as later modifications, e.g., the initial Privacy Profile choice and its later modification for scheme 3.

**Comment by bella-tassone** [comment]
Just took care of this. I believe it to be the only change necessary at this time.
