### ISSUE TITLE
Confirm that schemes 0 - 6 have domain list and scheme 7 does not

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-privacy-choice#251]
As the title says. I want to make 100% sure that this is the case. Because our interpretation of the data in our usability study will take a different turn depending on whether or not that is the case. So, if someone could confirm.

**Comment by JoeChampeau** [comment]
Just checked, there's no domain list on the Scheme 7 options page.

**Comment by SebastianZimmeck** [comment]
And also schemes 0 to 6 do indeed have the domain list?

**Comment by bella-tassone** [comment]
Scheme 7 is the only scheme not to have a domain list.

**Comment by SebastianZimmeck** [comment]
Great! Thanks for confirming!
