### ISSUE TITLE
Discuss/Outline Follow Up Longitudinal Usability Study

### ISSUE THREAD

**Issue by ekuller** [privacy-tech-lab/gpc-privacy-choice#253]
As discussed in the weekly meeting, it might be helpful to conduct a longitudinal usability study with a banner and non-banner to better gauge which people **relatively** prefer, when made explicitly aware of both possibilities. 

The need for this usability study will depend on the feedback from our paper submission, but in the meantime we may want to solidify a plan for conducting it.

**Comment by ekuller** [comment]
- [ ] technical hurdle -- clarify mechanics of the transition period from scheme 3 to scheme 7
- [ ] clarify number of people 
- [ ] draft survey and get it approved by IRB

**Comment by SebastianZimmeck** [comment]
I am closing this issue as we won't be doing a longitudinal study for the time being.
